// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package patient

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type NewPatientFormData struct {
	Error       string
	FormData    *PatientFormValues
	ServerError string
}

type PatientFormValues struct {
	Name       string
	Gender     string
	Ethnicity  string
	Occupation string
	Education  string
	Notes      string
}

func NewPatientForm(data NewPatientFormData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"form-container\"><div class=\"content-header\"><div class=\"header-title\"><div class=\"header-title-row\"><a href=\"/patients\" class=\"btn btn-ghost btn-sm\" aria-label=\"Voltar para a lista de pacientes\"><i class=\"fas fa-arrow-left btn-icon\"></i></a><div><h1>Novo Paciente</h1><p class=\"header-subtitle\">Cadastre um novo paciente para iniciar o acompanhamento clínico</p></div></div></div></div><div class=\"clinical-notebook-form\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.Error != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"form-error\" role=\"alert\" aria-live=\"polite\"><p><i class=\"fas fa-exclamation-circle\"></i> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.Error)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/patient/new_form.templ`, Line: 45, Col: 18}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if data.ServerError != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"form-error\" role=\"alert\" aria-live=\"polite\"><p><i class=\"fas fa-exclamation-circle\"></i> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.ServerError)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/patient/new_form.templ`, Line: 54, Col: 24}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<form action=\"/patients/create\" method=\"POST\"><div class=\"identity-section\"><div class=\"silent-form-group\"><label class=\"silent-label\" for=\"patient-name\">Nome Completo *</label> <input id=\"patient-name\" type=\"text\" name=\"name\" required autocomplete=\"name\" placeholder=\"Ex: Maria da Silva\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(data.FormData.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/patient/new_form.templ`, Line: 72, Col: 33}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" class=\"silent-input patient-name-input\" aria-describedby=\"patient-name-help\"><p id=\"patient-name-help\" class=\"small\">Use o nome pelo qual o paciente deve ser identificado no prontuário.</p></div><div class=\"biopsychosocial-grid\"><div class=\"silent-form-group\"><label class=\"silent-label\" for=\"patient-gender\">Identidade de Gênero</label> <input id=\"patient-gender\" type=\"text\" name=\"gender\" autocomplete=\"sex\" placeholder=\"Ex: Feminino, Masculino, Não-binário\" class=\"silent-input\"></div><div class=\"silent-form-group\"><label class=\"silent-label\" for=\"patient-ethnicity\">Etnia/Raça</label> <input id=\"patient-ethnicity\" type=\"text\" name=\"ethnicity\" placeholder=\"Ex: Branca, Preta, Parda, Amarela, Indígena\" class=\"silent-input\"></div><div class=\"silent-form-group\"><label class=\"silent-label\" for=\"patient-occupation\">Ocupação</label> <input id=\"patient-occupation\" type=\"text\" name=\"occupation\" placeholder=\"Ex: Estudante, Advogado, Autônomo\" class=\"silent-input\"></div><div class=\"silent-form-group\"><label class=\"silent-label\" for=\"patient-education\">Escolaridade</label> <input id=\"patient-education\" type=\"text\" name=\"education\" placeholder=\"Ex: Ensino Médio, Superior, Pós-graduação\" class=\"silent-input\"></div></div></div><div class=\"anamnesis-section\"><div class=\"silent-form-group\"><label class=\"silent-label\" for=\"patient-notes\">Observações Iniciais</label> <textarea id=\"patient-notes\" name=\"notes\" rows=\"8\" placeholder=\"Descreva observações relevantes sobre o paciente:&#10;&#10;- Queixa principal&#10;- Histórico clínico relevante&#10;- Contexto biopsicossocial&#10;- Encaminhamentos anteriores\" class=\"silent-textarea clinical-textarea\" aria-describedby=\"patient-notes-help\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(data.FormData.Notes)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/patient/new_form.templ`, Line: 149, Col: 28}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</textarea><p id=\"patient-notes-help\" class=\"small\">Essas notas ficarão visíveis no perfil do paciente para consulta rápida durante as sessões.</p></div></div><div class=\"form-actions\"><a href=\"/patients\" class=\"btn btn-outline\"><i class=\"fas fa-times btn-icon\"></i> Cancelar</a> <button type=\"submit\" class=\"btn btn-primary\"><i class=\"fas fa-user-plus btn-icon\"></i> Cadastrar Paciente</button></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
