// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package session

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func InterventionForm(sessionID string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form hx-post=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(templ.URL("/sessions/" + sessionID + "/interventions"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/components/session/intervention_form.templ`, Line: 5, Col: 66}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" hx-target=\"#interventions-list\" hx-swap=\"afterbegin\" hx-on::after-request=\"this.reset()\" style=\"margin-top: var(--space-lg); padding-top: var(--space-lg); border-top: 1px solid var(--neutral-100);\"><div style=\"margin-bottom: var(--space-md);\"><label for=\"intervention-content\" style=\"display: block; font-family: var(--font-sans); font-size: 0.75rem; font-weight: 500; color: var(--neutral-500); text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: var(--space-sm);\"><i class=\"fas fa-hands-helping\" style=\"margin-right: var(--space-xs);\"></i> Nova Intervenção Terapêutica</label> <textarea id=\"intervention-content\" name=\"content\" placeholder=\"Descreva a técnica ou intervenção realizada...\" rows=\"4\" style=\"width: 100%; background: var(--neutral-50); border: none; border-radius: var(--radius-lg); padding: var(--space-8); font-family: var(--font-clinical); font-size: 1.125rem; line-height: 1.75; color: var(--neutral-800); resize: vertical; transition: background-color 0.2s ease, box-shadow 0.2s ease;\" onfocus=\"this.style.background='white'; this.style.boxShadow='inset 0 2px 4px rgba(0,0,0,0.05)'; this.style.outline='none';\" onblur=\"this.style.background='var(--neutral-50)'; this.style.boxShadow='none';\" required></textarea><div style=\"font-size: 0.75rem; color: var(--neutral-400); margin-top: var(--space-xs); font-style: italic;\"><i class=\"fas fa-info-circle\"></i> Registre a conduta técnica aplicada para análise posterior da evolução.</div></div><div class=\"form-actions\"><button type=\"submit\" class=\"btn btn-secondary\"><i class=\"fas fa-plus btn-icon\"></i>Adicionar Intervenção</button> <button type=\"button\" class=\"btn btn-outline\" onclick=\"this.closest('form').querySelector('textarea').value = ''\"><i class=\"fas fa-times btn-icon\"></i>Limpar</button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
